name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/moonmodules/WLED/archive/refs/heads/mdev.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32s2_PSRAM_M' >>platformio.ini
        echo 'build_flags = ${env:esp32s2_PSRAM_M.build_flags} ${common.debug_flags} -D SR_DEBUG -D MIC_LOGGER -D LEDPIN=16 -D WLED_MAX_USERMODS=6 -D USERMOD_DALLASTEMPERATURE -D USERMOD_AUTO_SAVE -D USERMOD_BATTERY -D USERMOD_SENSORSTOMQTT -D USERMOD_RTC -D USERMOD_SN_PHOTORESISTOR' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32s2_PSRAM_M.lib_deps}' >>platformio.ini
        echo '  OneWire@~2.3.5' >>platformio.ini
        echo '  adafruit/Adafruit BMP280 Library @ 2.1.0' >>platformio.ini
        echo '  adafruit/Adafruit CCS811 Library @ 1.0.4' >>platformio.ini
        echo '  adafruit/Adafruit Si7021 Library @ 1.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
